In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load datasets
nav = pd.read_csv("data/processed/nav_history_clean.csv")
performance = pd.read_csv("data/generated/scheme_performance.csv")

# Convert date column
nav["date"] = pd.to_datetime(nav["date"])

print("NAV Dataset Shape:", nav.shape)
print("Performance Dataset Shape:", performance.shape)

nav.head()

NAV Dataset Shape: (16786, 7)
Performance Dataset Shape: (10, 7)

,scheme_code,scheme_name,fund_house,scheme_type,scheme_category,date,nav
0,118632,Nippon Large Cap Direct,Nippon India Mutual Fund,Open Ended Schemes,Equity Scheme - Large Cap Fund,2013-01-02,14.6967
1,118632,Nippon Large Cap Direct,Nippon India Mutual Fund,Open Ended Schemes,Equity Scheme - Large Cap Fund,2013-01-03,14.7305
2,118632,Nippon Large Cap Direct,Nippon India Mutual Fund,Open Ended Schemes,Equity Scheme - Large Cap Fund,2013-01-04,14.8037
3,118632,Nippon Large Cap Direct,Nippon India Mutual Fund,Open Ended Schemes,Equity Scheme - Large Cap Fund,2013-01-07,14.7718
4,118632,Nippon Large Cap Direct,Nippon India Mutual Fund,Open Ended Schemes,Equity Scheme - Large Cap Fund,2013-01-08,14.7197

In [4]:
# Compute Daily Returns
nav = nav.sort_values(["scheme_name", "date"])

nav["daily_return"] = nav.groupby("scheme_name")["nav"].pct_change()

# Display first few rows
nav.head(10)

,scheme_code,scheme_name,fund_house,scheme_type,scheme_category,date,nav,daily_return
3314,119092,Axis Bluechip Direct,HDFC Mutual Fund,Open Ended Schemes,Debt Scheme - Money Market Fund,2012-12-31,23.9920,NaN
3315,119092,Axis Bluechip Direct,HDFC Mutual Fund,Open Ended Schemes,Debt Scheme - Money Market Fund,2013-01-01,23.9979,0.000246
3316,119092,Axis Bluechip Direct,HDFC Mutual Fund,Open Ended Schemes,Debt Scheme - Money Market Fund,2013-01-02,24.0036,0.000238
3317,119092,Axis Bluechip Direct,HDFC Mutual Fund,Open Ended Schemes,Debt Scheme - Money Market Fund,2013-01-03,24.0092,0.000233
3318,119092,Axis Bluechip Direct,HDFC Mutual Fund,Open Ended Schemes,Debt Scheme - Money Market Fund,2013-01-04,24.0147,0.000229
3319,119092,Axis Bluechip Direct,HDFC Mutual Fund,Open Ended Schemes,Debt Scheme - Money Market Fund,2013-01-06,24.0258,0.000462
3320,119092,Axis Bluechip Direct,HDFC Mutual Fund,Open Ended Schemes,Debt Scheme - Money Market Fund,2013-01-07,24.0314,0.000233
3321,119092,Axis Bluechip Direct,HDFC Mutual Fund,Open Ended Schemes,Debt Scheme - Money Market Fund,2013-01-08,24.0369,0.000229
3322,119092,Axis Bluechip Direct,HDFC Mutual Fund,Open Ended Schemes,Debt Scheme - Money Market Fund,2013-01-09,24.0424,0.000229
3323,119092,Axis Bluechip Direct,HDFC Mutual Fund,Open Ended Schemes,Debt Scheme - Money Market Fund,2013-01-10,24.0479,0.000229

In [5]:
# Summary statistics of daily returns
nav["daily_return"].describe()

count    16781.000000
mean         0.006350
std          0.764600
min         -0.129512
25%         -0.000656
50%          0.000245
75%          0.002424
max         99.042353
Name: daily_return, dtype: float64

In [6]:
nav.sort_values("daily_return", ascending=False)[
    ["scheme_name", "date", "nav", "daily_return"]
].head(10)

                     scheme_name       date        nav  daily_return
4119        Axis Bluechip Direct 2015-08-30  3023.4700     99.042353
9661         SBI Bluechip Direct 2024-06-24   117.8708      0.128260
15254      Kotak Bluechip Direct 2020-04-07    46.7150      0.070446
1782     Nippon Large Cap Direct 2020-04-07    26.1117      0.070415
15244      Kotak Bluechip Direct 2020-03-20    45.0055      0.069029
11929  ICICI Pru Bluechip Direct 2020-04-07    41.8335      0.065615
11797  ICICI Pru Bluechip Direct 2019-09-20    49.5049      0.062809
15122      Kotak Bluechip Direct 2019-09-20    52.9228      0.061941
1650     Nippon Large Cap Direct 2019-09-20    35.1050      0.060898
11922  ICICI Pru Bluechip Direct 2020-03-25    40.4084      0.051043

In [7]:
nav.sort_values("daily_return")[
    ["scheme_name", "date", "nav", "daily_return"]
].head(10)

                     scheme_name       date       nav  daily_return
1773     Nippon Large Cap Direct 2020-03-23   23.4673     -0.129512
11920  ICICI Pru Bluechip Direct 2020-03-23   37.6463     -0.122362
9662         SBI Bluechip Direct 2024-06-25  104.5405     -0.113092
15245      Kotak Bluechip Direct 2020-03-23   40.4996     -0.100119
1766     Nippon Large Cap Direct 2020-03-12   29.1242     -0.090059
8992         SBI Bluechip Direct 2021-09-15  131.1996     -0.089683
16280      Kotak Bluechip Direct 2024-06-04  246.1066     -0.087819
8941         SBI Bluechip Direct 2021-06-30  141.9021     -0.085174
9057         SBI Bluechip Direct 2021-12-22  120.8645     -0.085146
15238      Kotak Bluechip Direct 2020-03-12   49.2353     -0.077028

In [8]:
nav[
    (nav["scheme_name"] == "Axis Bluechip Direct") &
    (nav["date"] >= "2015-08-20") &
    (nav["date"] <= "2015-09-10")
]

,scheme_code,scheme_name,fund_house,scheme_type,scheme_category,date,nav,daily_return
4111,119092,Axis Bluechip Direct,HDFC Mutual Fund,Open Ended Schemes,Debt Scheme - Money Market Fund,2015-08-20,30.1712,0.000209
4112,119092,Axis Bluechip Direct,HDFC Mutual Fund,Open Ended Schemes,Debt Scheme - Money Market Fund,2015-08-21,30.1777,0.000215
4113,119092,Axis Bluechip Direct,HDFC Mutual Fund,Open Ended Schemes,Debt Scheme - Money Market Fund,2015-08-23,30.1905,0.000424
4114,119092,Axis Bluechip Direct,HDFC Mutual Fund,Open Ended Schemes,Debt Scheme - Money Market Fund,2015-08-24,30.1967,0.000205
4115,119092,Axis Bluechip Direct,HDFC Mutual Fund,Open Ended Schemes,Debt Scheme - Money Market Fund,2015-08-25,30.2030,0.000209
4116,119092,Axis Bluechip Direct,HDFC Mutual Fund,Open Ended Schemes,Debt Scheme - Money Market Fund,2015-08-26,30.2093,0.000209
4117,119092,Axis Bluechip Direct,HDFC Mutual Fund,Open Ended Schemes,Debt Scheme - Money Market Fund,2015-08-27,30.2156,0.000209
4118,119092,Axis Bluechip Direct,HDFC Mutual Fund,Open Ended Schemes,Debt Scheme - Money Market Fund,2015-08-28,30.2219,0.000209
4119,119092,Axis Bluechip Direct,HDFC Mutual Fund,Open Ended Schemes,Debt Scheme - Money Market Fund,2015-08-30,3023.4700,99.042353
4120,119092,Axis Bluechip Direct,HDFC Mutual Fund,Open Ended Schemes,Debt Scheme - Money Market Fund,2015-08-31,3024.0940,0.000206
4121,119092,Axis Bluechip Direct,HDFC Mutual Fund,Open Ended Schemes,Debt Scheme - Money Market Fund,2015-09-01,3024.7217,0.000208
4122,119092,Axis Bluechip Direct,HDFC Mutual Fund,Open Ended Schemes,Debt Scheme - Money Market Fund,2015-09-02,3025.3461,0.000206
4123,119092,Axis Bluechip Direct,HDFC Mutual Fund,Open Ended Schemes,Debt Scheme - Money Market Fund,2015-09-03,3025.9735,0.000207
4124,119092,Axis Bluechip Direct,HDFC Mutual Fund,Open Ended Schemes,Debt Scheme - Money Market Fund,2015-09-04,3026.5983,0.000206
4125,119092,Axis Bluechip Direct,HDFC Mutual Fund,Open Ended Schemes,Debt Scheme - Money Market Fund,2015-09-06,3027.9099,0.000433
4126,119092,Axis Bluechip Direct,HDFC Mutual Fund,Open Ended Schemes,Debt Scheme - Money Market Fund,2015-09-07,3028.5349,0.000206
4127,119092,Axis Bluechip Direct,HDFC Mutual Fund,Open Ended Schemes,Debt Scheme - Money Market Fund,2015-09-08,3029.1560,0.000205
4128,119092,Axis Bluechip Direct,HDFC Mutual Fund,Open Ended Schemes,Debt Scheme - Money Market Fund,2015-09-09,3029.7792,0.000206
4129,119092,Axis Bluechip Direct,HDFC Mutual Fund,Open Ended Schemes,Debt Scheme - Money Market Fund,2015-09-10,3030.3753,0.000197

In [9]:
nav[abs(nav["daily_return"]) > 0.5][
    ["scheme_name", "date", "nav", "daily_return"]
]

               scheme_name       date      nav  daily_return
4119  Axis Bluechip Direct 2015-08-30  3023.47     99.042353

In [13]:
# Temporary correction for analysis only
# Original CSV file is NOT modified.

mask = (nav["scheme_name"] == "Axis Bluechip Direct") & (nav["date"] >= "2015-08-30")

nav.loc[mask, "nav"] = nav.loc[mask, "nav"] / 100

In [14]:
nav = nav.sort_values(["scheme_name", "date"])

nav["daily_return"] = nav.groupby("scheme_name")["nav"].pct_change()

nav["daily_return"].describe()

count    16781.000000
mean         0.000389
std          0.011100
min         -0.989996
25%         -0.000656
50%          0.000245
75%          0.002422
max          0.128260
Name: daily_return, dtype: float64

In [12]:
nav["daily_return"].describe()

count    16781.000000
mean         0.000448
std          0.008046
min         -0.129512
25%         -0.000656
50%          0.000245
75%          0.002422
max          0.128260
Name: daily_return, dtype: float64

In [15]:
# CAGR Calculation

cagr_results = []

for scheme, group in nav.groupby("scheme_name"):
    group = group.sort_values("date")

    end_nav = group.iloc[-1]["nav"]
    end_date = group.iloc[-1]["date"]

    result = {"scheme_name": scheme}

    for years in [1, 3, 5]:
        start_date = end_date - pd.DateOffset(years=years)
        past = group[group["date"] <= start_date]

        if len(past) > 0:
            start_nav = past.iloc[-1]["nav"]
            cagr = (end_nav / start_nav) ** (1 / years) - 1
            result[f"CAGR_{years}Y"] = cagr
        else:
            result[f"CAGR_{years}Y"] = np.nan

    cagr_results.append(result)

cagr_df = pd.DataFrame(cagr_results)

cagr_df

                 scheme_name   CAGR_1Y   CAGR_3Y   CAGR_5Y
0       Axis Bluechip Direct  0.062294  0.073645  0.065524
1  ICICI Pru Bluechip Direct -0.003818  0.114677  0.083134
2      Kotak Bluechip Direct  0.031841  0.177321  0.179756
3    Nippon Large Cap Direct  0.005481  0.152557  0.162784
4        SBI Bluechip Direct -0.013184 -0.019646 -0.073298

In [16]:
# Sharpe Ratio Calculation

risk_free_rate = 0.065  # 6.5% annual
daily_rf = risk_free_rate / 252

sharpe_results = []

for scheme, group in nav.groupby("scheme_name"):

    returns = group["daily_return"].dropna()

    if len(returns) > 0:

        sharpe = ((returns.mean() - daily_rf) / returns.std()) * np.sqrt(252)

        sharpe_results.append({
            "scheme_name": scheme,
            "Sharpe_Ratio": sharpe
        })

sharpe_df = pd.DataFrame(sharpe_results)

sharpe_df = sharpe_df.sort_values(
    "Sharpe_Ratio",
    ascending=False
)

sharpe_df

                 scheme_name  Sharpe_Ratio
2      Kotak Bluechip Direct      0.691435
1  ICICI Pru Bluechip Direct      0.628265
3    Nippon Large Cap Direct      0.570982
0       Axis Bluechip Direct     -0.258209
4        SBI Bluechip Direct     -0.676756

In [17]:
nav["scheme_name"].nunique()

5

In [19]:
# Sortino Ratio Calculation

risk_free_rate = 0.065
daily_rf = risk_free_rate / 252

sortino_results = []

for scheme, group in nav.groupby("scheme_name"):

    returns = group["daily_return"].dropna()

    downside_returns = returns[returns < daily_rf]

    if len(downside_returns) > 0:

        downside_std = downside_returns.std()

        sortino = ((returns.mean() - daily_rf) / downside_std) * np.sqrt(252)

    else:
        sortino = np.nan

    sortino_results.append({
        "scheme_name": scheme,
        "Sortino_Ratio": sortino
    })

sortino_df = pd.DataFrame(sortino_results)

sortino_df = sortino_df.sort_values(
    "Sortino_Ratio",
    ascending=False
)

sortino_df

                 scheme_name  Sortino_Ratio
2      Kotak Bluechip Direct       0.812438
1  ICICI Pru Bluechip Direct       0.784093
3    Nippon Large Cap Direct       0.709848
0       Axis Bluechip Direct      -0.214622
4        SBI Bluechip Direct      -0.525504

In [20]:
import os

os.listdir("data/raw")

['.gitkeep',
 'all_live_nav_combined.csv',
 'live_nav_118632_Nippon_Large_Cap_Direct.csv',
 'live_nav_119092_Axis_Bluechip_Direct.csv',
 'live_nav_119551_SBI_Bluechip_Direct.csv',
 'live_nav_120503_ICICI_Pru_Bluechip_Direct.csv',
 'live_nav_120841_Kotak_Bluechip_Direct.csv']

In [21]:
# Maximum Drawdown Calculation

drawdown_results = []

for scheme, group in nav.groupby("scheme_name"):

    group = group.sort_values("date").copy()

    group["Running_Max"] = group["nav"].cummax()

    group["Drawdown"] = (group["nav"] / group["Running_Max"]) - 1

    max_dd = group["Drawdown"].min()

    worst_row = group.loc[group["Drawdown"].idxmin()]

    drawdown_results.append({
        "scheme_name": scheme,
        "Maximum_Drawdown": max_dd,
        "Worst_Date": worst_row["date"]
    })

drawdown_df = pd.DataFrame(drawdown_results)

drawdown_df = drawdown_df.sort_values(
    "Maximum_Drawdown"
)

drawdown_df

                 scheme_name  Maximum_Drawdown Worst_Date
0       Axis Bluechip Direct         -0.989996 2015-08-30
3    Nippon Large Cap Direct         -0.399608 2020-03-23
4        SBI Bluechip Direct         -0.366517 2024-12-20
1  ICICI Pru Bluechip Direct         -0.335099 2020-03-23
2      Kotak Bluechip Direct         -0.334299 2020-03-23

In [22]:
nav[
    (nav["scheme_name"] == "Axis Bluechip Direct") &
    (nav["date"] >= "2015-08-28") &
    (nav["date"] <= "2015-09-02")
][["date","nav"]]

           date        nav
4118 2015-08-28  30.221900
4119 2015-08-30   0.302347
4120 2015-08-31   0.302409
4121 2015-09-01   0.302472
4122 2015-09-02   0.302535

In [23]:
nav.loc[
    (nav["scheme_name"]=="Axis Bluechip Direct") &
    (nav["date"]>="2015-08-30"),
    "nav"
].head()

4119    0.302347
4120    0.302409
4121    0.302472
4122    0.302535
4123    0.302597
Name: nav, dtype: float64

In [24]:
mask = (nav["scheme_name"] == "Axis Bluechip Direct") & (nav["date"] >= "2015-08-30")

nav.loc[mask, "nav"] = nav.loc[mask, "nav"] * 100

In [25]:
nav[
    (nav["scheme_name"]=="Axis Bluechip Direct") &
    (nav["date"]>="2015-08-28") &
    (nav["date"]<="2015-09-02")
][["date","nav"]]

           date        nav
4118 2015-08-28  30.221900
4119 2015-08-30  30.234700
4120 2015-08-31  30.240940
4121 2015-09-01  30.247217
4122 2015-09-02  30.253461

In [26]:
nav = nav.sort_values(["scheme_name", "date"])

nav["daily_return"] = nav.groupby("scheme_name")["nav"].pct_change()

In [27]:
drawdown_results = []

for scheme, group in nav.groupby("scheme_name"):

    group = group.sort_values("date").copy()

    group["Running_Max"] = group["nav"].cummax()

    group["Drawdown"] = (group["nav"] / group["Running_Max"]) - 1

    max_dd = group["Drawdown"].min()

    worst_row = group.loc[group["Drawdown"].idxmin()]

    drawdown_results.append({
        "scheme_name": scheme,
        "Maximum_Drawdown": max_dd,
        "Worst_Date": worst_row["date"]
    })

drawdown_df = pd.DataFrame(drawdown_results)

drawdown_df = drawdown_df.sort_values("Maximum_Drawdown")

drawdown_df

                 scheme_name  Maximum_Drawdown Worst_Date
3    Nippon Large Cap Direct         -0.399608 2020-03-23
4        SBI Bluechip Direct         -0.366517 2024-12-20
1  ICICI Pru Bluechip Direct         -0.335099 2020-03-23
2      Kotak Bluechip Direct         -0.334299 2020-03-23
0       Axis Bluechip Direct         -0.013924 2020-03-24

In [28]:
# Fund Scorecard (Temporary - Without Alpha)

scorecard = cagr_df.merge(sharpe_df, on="scheme_name")
scorecard = scorecard.merge(drawdown_df, on="scheme_name")

# Ranking
scorecard["Return_Rank"] = scorecard["CAGR_3Y"].rank(ascending=False)
scorecard["Sharpe_Rank"] = scorecard["Sharpe_Ratio"].rank(ascending=False)
scorecard["Drawdown_Rank"] = scorecard["Maximum_Drawdown"].rank(ascending=False)

# Temporary score
scorecard["Fund_Score"] = (
    scorecard["Return_Rank"] * 0.5 +
    scorecard["Sharpe_Rank"] * 0.3 +
    scorecard["Drawdown_Rank"] * 0.2
)

scorecard = scorecard.sort_values("Fund_Score")

scorecard

,scheme_name,CAGR_1Y,CAGR_3Y,CAGR_5Y,Sharpe_Ratio,Maximum_Drawdown,Worst_Date,Return_Rank,Sharpe_Rank,Drawdown_Rank,Fund_Score
2,Kotak Bluechip Direct,0.031841,0.177321,0.179756,0.691435,-0.334299,2020-03-23,1.0,1.0,2.0,1.2
1,ICICI Pru Bluechip Direct,-0.003818,0.114677,0.083134,0.628265,-0.335099,2020-03-23,3.0,2.0,3.0,2.7
3,Nippon Large Cap Direct,0.005481,0.152557,0.162784,0.570982,-0.399608,2020-03-23,2.0,3.0,5.0,2.9
0,Axis Bluechip Direct,0.062294,0.073645,0.065524,-0.258209,-0.013924,2020-03-24,4.0,4.0,1.0,3.4
4,SBI Bluechip Direct,-0.013184,-0.019646,-0.073298,-0.676756,-0.366517,2024-12-20,5.0,5.0,4.0,4.8

In [29]:
scorecard.to_csv("fund_scorecard.csv", index=False)

In [30]:
!pip install yfinance

Collecting yfinance
  Downloading yfinance-1.4.1-py2.py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: pandas>=1.3.0 in c:\projects\mutual_fund_analytics\venv314\lib\site-packages (from yfinance) (3.0.3)
Requirement already satisfied: numpy>=1.16.5 in c:\projects\mutual_fund_analytics\venv314\lib\site-packages (from yfinance) (2.5.0)
Requirement already satisfied: requests>=2.31 in c:\projects\mutual_fund_analytics\venv314\lib\site-packages (from yfinance) (2.34.2)
Collecting multitasking>=0.0.7 (from yfinance)
  Downloading multitasking-0.0.13-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: platformdirs>=2.0.0 in c:\projects\mutual_fund_analytics\venv314\lib\site-packages (from yfinance) (4.10.0)
Collecting pytz>=2022.5 (from yfinance)
  Using cached pytz-2026.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting peewee>=3.16.2 (from yfinance)
  Downloading peewee-4.1.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\projects\mutual_fund_analytics\venv314\lib\site-packages (from yfinance) (4.15.0)
Collecting curl_cffi>=0.15 (from yfinance)
  Downloading curl_cffi-0.15.0-cp310-abi3-win_amd64.whl.metadata (18 kB)
Collecting protobuf>=3.19.0 (from yfinance)
  Downloading protobuf-7.35.1-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Collecting websockets>=13.0 (from yfinance)
  Using cached websockets-16.0-cp314-cp314-win_amd64.whl.metadata (7.0 kB)
Requirement already satisfied: soupsieve>=1.6.1 in c:\projects\mutual_fund_analytics\venv314\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\projects\mutual_fund_analytics\venv314\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in c:\projects\mutual_fund_analytics\venv314\lib\site-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in c:\projects\mutual_fund_analytics\venv314\lib\site-packages (from curl_cffi>=0.15->yfinance) (2026.6.17)
Collecting rich (from curl_cffi>=0.15->yfinance)
  Downloading rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: pycparser in c:\projects\mutual_fund_analytics\venv314\lib\site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\projects\mutual_fund_analytics\venv314\lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\projects\mutual_fund_analytics\venv314\lib\site-packages (from pandas>=1.3.0->yfinance) (2026.2)
Requirement already satisfied: six>=1.5 in c:\projects\mutual_fund_analytics\venv314\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\projects\mutual_fund_analytics\venv314\lib\site-packages (from requests>=2.31->yfinance) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\projects\mutual_fund_analytics\venv314\lib\site-packages (from requests>=2.31->yfinance) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in c:\projects\mutual_fund_analytics\venv314\lib\site-packages (from requests>=2.31->yfinance) (2.7.0)
Collecting markdown-it-py>=2.2.0 (from rich->curl_cffi>=0.15->yfinance)
  Downloading markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\projects\mutual_fund_analytics\venv314\lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (2.20.0)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading yfinance-1.4.1-py2.py3-none-any.whl (137 kB)
Downloading curl_cffi-0.15.0-cp310-abi3-win_amd64.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.7 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.7 MB ? eta -:--:--
   ------------ --------------------------- 0.5/1.7 MB 646.2 kB/s eta 0:00:02
   ------------------ --------------------- 0.8/1.7 MB 775.5 kB/s eta 0:00:02
   ------------------ --------------------- 0.8/1.7 MB 775.5 kB/s eta 0:00:02
   ------------------------- -------------- 1.0/1.7 MB 850.3 kB/s eta 0:00:01
   ------------------------------- -------- 1.3/1.7 MB 839.2 kB/s eta 0:00:01
   ------------------------------------- -- 1.6/1.7 MB 900.0 kB/s eta 0:00:01
   ---------------------------------------- 1.7/1.7 MB 901.1 kB/s  0:00:01
Downloading multitasking-0.0.13-py3-none-any.whl (16 kB)
Downloading peewee-4.1.1-py3-none-any.whl (170 kB)
Downloading protobuf-7.35.1-cp310-abi3-win_amd64.whl (439 kB)
Using cached pytz-2026.2-py2.py3-none-any.whl (510 kB)
Using cached websockets-16.0-cp314-cp314-win_amd64.whl (178 kB)
Downloading rich-15.0.0-py3-none-any.whl (310 kB)
Downloading markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: pytz, peewee, multitasking, websockets, protobuf, mdurl, markdown-it-py, rich, curl_cffi, yfinance

   ----------------------------------------  0/10 [pytz]
   ----------------------------------------  0/10 [pytz]
   ----------------------------------------  0/10 [pytz]
   ----------------------------------------  0/10 [pytz]
   ----------------------------------------  0/10 [pytz]
   ----------------------------------------  0/10 [pytz]
   ----------------------------------------  0/10 [pytz]
   ----------------------------------------  0/10 [pytz]
   ----------------------------------------  0/10 [pytz]
   ---- -----------------------------------  1/10 [peewee]
   ---- -----------------------------------  1/10 [peewee]
   ---- -----------------------------------  1/10 [peewee]
   ---- -----------------------------------  1/10 [peewee]
   ---- -----------------------------------  1/10 [peewee]
   ------------ ---------------------------  3/10 [websockets]
   ------------ ---------------------------  3/10 [websockets]
   ------------ ---------------------------  3/10 [websockets]
   ------------ ---------------------------  3/10 [websockets]
   ------------ ---------------------------  3/10 [websockets]
   ------------ ---------------------------  3/10 [websockets]
   ------------ ---------------------------  3/10 [websockets]
   ---------------- -----------------------  4/10 [protobuf]
   ---------------- -----------------------  4/10 [protobuf]
   ---------------- -----------------------  4/10 [protobuf]
   ---------------- -----------------------  4/10 [protobuf]
   ---------------- -----------------------  4/10 [protobuf]
   ---------------- -----------------------  4/10 [protobuf]
   ---------------- -----------------------  4/10 [protobuf]
   -------------------- -------------------  5/10 [mdurl]
   ------------------------ ---------------  6/10 [markdown-it-py]
   ------------------------ ---------------  6/10 [markdown-it-py]
   ------------------------ ---------------  6/10 [markdown-it-py]
   ------------------------ ---------------  6/10 [markdown-it-py]
   ------------------------ ---------------  6/10 [markdown-it-py]
   ------------------------ ---------------  6/10 [markdown-it-py]
   ---------------------------- -----------  7/10 [rich]
   ---------------------------- -----------  7/10 [rich]
   ---------------------------- -----------  7/10 [rich]
   ---------------------------- -----------  7/10 [rich]
   ---------------------------- -----------  7/10 [rich]
   ---------------------------- -----------  7/10 [rich]
   ---------------------------- -----------  7/10 [rich]
   ---------------------------- -----------  7/10 [rich]
   ---------------------------- -----------  7/10 [rich]
   ---------------------------- -----------  7/10 [rich]
   ---------------------------- -----------  7/10 [rich]
   ---------------------------- -----------  7/10 [rich]
   ---------------------------- -----------  7/10 [rich]
   ---------------------------- -----------  7/10 [rich]
   ---------------------------- -----------  7/10 [rich]
   -------------------------------- -------  8/10 [curl_cffi]
   -------------------------------- -------  8/10 [curl_cffi]
   -------------------------------- -------  8/10 [curl_cffi]
   ------------------------------------ ---  9/10 [yfinance]
   ------------------------------------ ---  9/10 [yfinance]
   ------------------------------------ ---  9/10 [yfinance]
   ------------------------------------ ---  9/10 [yfinance]
   ------------------------------------ ---  9/10 [yfinance]
   ------------------------------------ ---  9/10 [yfinance]
   ---------------------------------------- 10/10 [yfinance]

Successfully installed curl_cffi-0.15.0 markdown-it-py-4.2.0 mdurl-0.1.2 multitasking-0.0.13 peewee-4.1.1 protobuf-7.35.1 pytz-2026.2 rich-15.0.0 websockets-16.0 yfinance-1.4.1

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [31]:
import yfinance as yf

nifty100 = yf.download("^CNX100", start="2013-01-01", end="2026-06-28")

nifty100.head()

[*********************100%***********************]  1 of 1 completed

Price             Close         High          Low         Open   Volume
Ticker          ^CNX100      ^CNX100      ^CNX100      ^CNX100  ^CNX100
Date
2013-01-01  5896.899902  5908.000000  5875.149902  5875.149902  1590200
2013-01-02  5938.200195  5952.299805  5923.950195  5923.950195  2161100
2013-01-03  5956.549805  5962.000000  5931.600098  5957.399902  2089100
2013-01-04  5961.250000  5965.399902  5927.850098  5958.649902  2865500
2013-01-07  5939.250000  5983.250000  5928.549805  5983.250000  2745300

In [32]:
nifty100.to_csv("data/raw/nifty100.csv")

In [33]:
import pandas as pd

# Read benchmark
nifty100 = pd.read_csv("data/raw/nifty100.csv")

# Flatten columns if needed
if isinstance(nifty100.columns, pd.MultiIndex):
    nifty100.columns = nifty100.columns.get_level_values(0)

# Rename Close column
nifty100 = nifty100.rename(columns={"Close": "benchmark_nav"})

# Convert date
nifty100["Date"] = pd.to_datetime(nifty100["Date"])

# Benchmark daily return
nifty100["benchmark_return"] = nifty100["benchmark_nav"].pct_change()

nifty100.head()

KeyError: 'Date'